import type { Metadata } from "next";
import localFont from 'next/font/local'
import '../app/styles/fonts.css'
import '../app/styles/reset.css'
import '../app/styles/globals.css'
import Footer from "./sections/Footer";
import Navigation from "./sections/Navigation";

// Local font
const PPMori = localFont({
  src: [
    {
      path: '../public/fonts/PPMori-Extralight.otf',
      weight: '300',
      style: 'normal',
    },
    {
      path: '../public/fonts/PPMori-ExtralightItalic.otf',
      weight: '300',
      style: 'italic',
    },
    {
      path: '../public/fonts/PPMori-Regular.otf',
      weight: '400',
      style: 'normal',
    },
    {
      path: '../public/fonts/PPMori-RegularItalic.otf',
      weight: '400',
      style: 'italic',
    },
    {
      path: '../public/fonts/PPMori-SemiBold.otf',
      weight: '700',
      style: 'normal',
    },
    {
      path: '../public/fonts/PPMori-SemiBoldItalic.otf',
      weight: '700',
      style: 'italic',
    },
  ],
  display: 'swap',
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en"> 
      <body className={`${PPMori.className} bg-color-light text-color-dark

          flex
          justify-center
          min-h-screen

      `}>
        <div className={`body-wrapper

            container 
            p-4
            lg:p-0
            flex
            flex-col

        `}>
            <Navigation />
            {children}
            <Footer />
        </div>
        
      </body>
    </html>
  );
}
